version: "3.8"
services:
  wg-easy:
    container_name: wg-easy
    image: weejewel/wg-easy:latest
    restart: always
    env_file:
      - wg.env
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    volumes:
      - ./wireguard/conf:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wireguard:
        ipv4_address: 172.18.0.2 #internal static ip

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    env_file:
      - pi-hole.env
    ports:
      - "54:53/tcp"
      - "54:53/udp"
      - "67:67/udp"
      - "83:80/tcp"
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    networks:
      wireguard:
        ipv4_address: 172.18.0.3 #internal static ip

networks:
  wireguard:
    ipam:
        driver: default
        config:
            - subnet: 172.18.0.0/16 ##internal subnet